### ISSUE TITLE
Correlation between pandapower and pandapipes

### ISSUE THREAD

**Issue by vahidsabzpoosh** [e2nIEE/pandapipes#186]
I would like to a start a discussion on how to establish a correlation between pipe and power networks?
In pandapipe pumps and sources are power consumption elements, but this feature didn't include. This issue is also present in pandapower, in which heat pump and pipe grid sources should consider as power loads. These should be taken into account on pipeflow and powerflow.  Also, the managing standard type section is still in process and it is not possible in this way either.

**Comment by jkisse** [comment]
Dear @vahidsabzpoosh,

thank you for your sharing your thoughts on this important topic. 
Actually, there has been some recent work on so-called "multi-nets" that can couple pandapower and pandapipes networks. It will be officially included in the next release. Until then, you can check out the preliminary development version on the [pandapipes/multinet branch](https://github.com/e2nIEE/pandapipes/tree/multinet). There is also [a tutorial](https://github.com/e2nIEE/pandapipes/blob/multinet/tutorials/coupled_nets_h2_p2g2p.ipynb) to get started with. A respective description can be found [here](https://pandapipes.readthedocs.io/en/multinet/multi_energy_nets.html) in the documentation.

Please note that only the coupling of power and gas networks has been implemented yet. In order to couple heat and power networks, a new power-to-heat controller similar to the power-to-gas-controller needs to be written. The code of the P2G-controller can be found [here](https://github.com/e2nIEE/pandapipes/blob/multinet/pandapipes/multinet/control/controller/multinet_control.py).

I hope this helps you. If you try out the new multinets, I'd be happy to hear your feedback.

**Comment by vahidsabzpoosh** [comment]
Daer jkisse
Hope you are fine.Thank you for your fast and complete response. I'm trying to use the multinet and get the output. I will definitely give you feedback on that
warm regards


    On Wednesday, December 23, 2020, 03:41:15 PM GMT+1, jkisse <notifications@github.com> wrote:  
 
 


Dear @vahidsabzpoosh,

thank you for your sharing your thoughts on this important topic.
Actually, there has been some recent work on so-called "multi-nets" that can couple pandapower and pandapipes networks. It will be officially included in the next release. Until then, you can check out the preliminary development version on the pandapipes/multinet branch. There is also a tutorial to get started with. A respective description can be found here in the documentation.

Please note that only the coupling of power and gas networks has been implemented yet. In order to couple heat and power networks, a new power-to-heat controller similar to the power-to-gas-controller needs to be written. The code of the P2G-controller can be found here.

I hope this helps you. If you try out the new multinets, I'd be happy to hear your feedback.

**Comment by vahidsabzpoosh** [comment]
HiI am trying to use the multinet package, but I am getting the below error when I run the given example for the coupled networks net_power = e_nw.example_simple() and net_gas = g_nw.gas_meshed_square():

File "C:\Users\anaconda3\lib\site-packages\pandapipes\pandapipes\multinet\control\run_control_multinet.py", line 140, in run_control    ctrl_variables = prepare_run_ctrl(multinet, ctrl_variables)
  File "C:\Users\anaconda3\lib\site-packages\pandapipes\pandapipes\multinet\control\run_control_multinet.py", line 234, in prepare_run_ctrl    raise ValueError('the given nets are neither pandapipes nor pandapower nets')
ValueError: the given nets are neither pandapipes nor pandapower nets
Would you please help me to solve this problem?
Thank you.
    On Wednesday, December 23, 2020, 03:41:15 PM GMT+1, jkisse <notifications@github.com> wrote:  
 
 


Dear @vahidsabzpoosh,

thank you for your sharing your thoughts on this important topic.
Actually, there has been some recent work on so-called "multi-nets" that can couple pandapower and pandapipes networks. It will be officially included in the next release. Until then, you can check out the preliminary development version on the pandapipes/multinet branch. There is also a tutorial to get started with. A respective description can be found here in the documentation.

Please note that only the coupling of power and gas networks has been implemented yet. In order to couple heat and power networks, a new power-to-heat controller similar to the power-to-gas-controller needs to be written. The code of the P2G-controller can be found here.

I hope this helps you. If you try out the new multinets, I'd be happy to hear your feedback.

**Comment by jkisse** [comment]
Hi @vahidsabzpoosh,

could you please provide a minimal example to reproduce the error?
I have set up the tutorial on Binder ([here](https://mybinder.org/v2/gh/e2nIEE/pandapipes/develop?filepath=tutorials%2Fcoupled_nets_h2_p2g2p.ipynb)) and it works fine, so there might be an issue with your local Python environment. 

The new pandapipes version (0.3.0) has been released today, as well as a new version of pandapower. Maybe updating the packages will help you to solve the error.

**Comment by dlohmeier** [comment]
@vahidsabzpoosh did you get along with the tutorial? If there aren't any errors, we would like to close this issue until the end of this week.

**Comment by vahidsabzpoosh** [comment]
Hi
yes I get it. There aren't any errors now. Thank you for your consideration.   On Monday, January 25, 2021, 11:31:25 AM GMT+1, Daniel Lohmeier <notifications@github.com> wrote:  
 
 


@vahidsabzpoosh did you get along with the tutorial? If there aren't any errors, we would like to close this issue until the end of this week.
