### ISSUE TITLE
Maximum iterations of Colebrook-White algorithm

### ISSUE THREAD

**Issue by dlohmeier** [e2nIEE/pandapipes#211]
I am currently running some calculations of different network topologies for a large gas network and found that the Colebrook-White algorithm does not use a limit for its iterations. However, in some cases the algorithm obviously does not converge, as I had to kill my script after nearly half a million iterations. I think it would be wise to implement a maximum number of iterations and use a normal pipeflow exception, if this number is reached. But endless loops should really be avoided.

@dcronbach do you have a suggestion on a suitable default number of maximum iterations?

**Comment by dcronbach** [comment]
If I remember correctly, the algorithm typically converges in only very few iterations. If you set it to 100, it might be more than enough. I would use this as a start and see, if this number has to be adapted in the future. 

Nevertheless, I do not know if this number is feasible, as I have not done larger calculations in pandapipes since ~1 year.

**Comment by dlohmeier** [comment]
Yes, I think that it should usually converge very fast. If it does not, that is probably caused by erroneous input data and accompanied by problems with the NR algorithm. So, if using the Nikuradse approach, the NR algorithm wouldn't converge either, so that throwing a ppException would totally make sense.
