### ISSUE TITLE
FlowController for heat networks

### ISSUE THREAD

**Issue by TheNeedForSleep** [e2nIEE/pandapipes#361]
Hello,

Im currently trying to regulate flow at heat_exchangers. I have created an `MaxFlowController` that continuously reduces the diameter of an object until the flow is lower than specified. This sadly leads to errors  which i suspect is caused when very large values are next to small values.

Id like to have the possibility to control the max_flow in heat_exchangers similar to the way it works with sinks.
Sinks allow to specify a fixed maximum mass flow.

Example: I have a (small part of a) district heating network with one single producer and n consumer. One of the consumers is very close to the producer. The producer is located on the top right. The closest consumer is the first orange marker right next to it. ~75% of the flow goes through the first consumer while only ~25% goes to the the rest of the network which is not the desired behaviour.
![image](https://user-images.githubusercontent.com/44329937/157642288-dfbfc7d3-7677-4d33-b01f-0df9d5a3bb03.png)

Would it be possible to implement such a feature?
Either extend:
- valve with max_flow
- make sink have an out_flow
- extend heat_exchanger with a max_flow

Best regards

**Comment by dlohmeier** [comment]
Hi @TheNeedForSleep ,
as @jkisse mentioned, there is a (still open) pull request for a new component, a flow control valve that exactly defines the flow going through. I think that would be a typical component for a heating grid. Is that what you were looking for? If you have any suggestions on how to adapt this model, please feel free to comment on the PR #413 . Otherwise we will merge it soon, but you could still make suggestions on improvement of course. Sorry for the late reply, but we have been busy on many gas grid related topics most of the time.
Best regards
