### ISSUE TITLE
KeyError: 'progress_bar' in run_timeseries()

### ISSUE THREAD

**Issue by Kupferbart** [e2nIEE/pandapipes#386]
**Describe the bug**
Following the [example](https://github.com/e2nIEE/pandapipes/blob/develop/tutorials/coupled_nets_h2_p2g2p.ipynb) hosted in the repo, I tried to run a timeseries calculation on a coupled multinet. A KeyError is thrown within the run_timeseries() function, as 'progress_bar' seems not to be in the keyset.

**To Reproduce**
Using purely the code outlined in the timeseries section of the example.

**Error message**
File "<path_to_project>\multinet.py", line 96, in <module>
    run_timeseries(multinet, time_steps=range(10), output_writers=ows)
  File "C:\Users\<User>\miniconda3\envs\panda\lib\site-packages\pandapipes\multinet\timeseries\run_time_series_multinet.py", line 126, in run_timeseries
    run_loop(multinet, ts_variables, run_control, _call_output_writer, **kwargs)
  File "C:\Users\<User>\miniconda3\envs\panda\lib\site-packages\pandapower\timeseries\run_time_series.py", line 320, in run_loop
    print_progress(i, time_step, ts_variables["time_steps"], ts_variables["verbose"], ts_variables=ts_variables,  
  File "C:\Users\<User>\miniconda3\envs\panda\lib\site-packages\pandapower\timeseries\run_time_series.py", line 297, in print_progress
    kwargs['ts_variables']["progress_bar"].update(1)
KeyError: 'progress_bar'

**Expected behavior**
The timeseries calculation shall finish without a (Key)Error thrown.

**Python environment:**
 - OS: Windows 10
 - pandapipes version: 0.6.0

**Comment by dlohmeier** [comment]
Hi @Kupferbart,
there is indeed still an error in version 0.6.0 for the multinet timeseries simulation. It has already been fixed on our current develop branch and we are planning a new release very soon. If you wait just a few days, we will inform you and you can update to the new version where the bug is fixed.

**Comment by Kupferbart** [comment]
Unfortunately your framework was part of a student project, which could not be finished to our satisfaction due to the bugs present.
I strongly suggest that you reevaluate how you handle bugfixes. When such an integral part of your framework is not working, it warrants a hotfix outside of the usual update schedule.
It is unacceptable to let your framework in a nonfunctioning state for so long.

**Comment by dlohmeier** [comment]
Dear @Kupferbart,
I am sorry to hear that the student project has been influenced by this problem. It's great to hear that someone has tried to make use of our multinet functionality. Obviously noone else tried this, otherwise we would have been informed and made the changes (including a hotfix) much sooner.
Unfortunately, pandapipes is not a project with large financial and human resources and is still officially in a beta stadium, so we rely on the community, on users and other developers to support us in making improvements and reporting and fixing bugs. If you identify another bug next time, I suggest that you open an issue immediately... otherwise it can hardly be expected that we solve the problem within a day or so.
Please be aware that pandapipes is an open source project, which is the only reason why you are allowed to simply use it for free and even take a look at the whole code to validate how it works. The downside of this is of course that we cannot be held responsible for every problem that users face, so "unacceptable" is definitely the wrong term for our response time as well as the release cycles.
As I pointed out, we are going to release a new version very soon anyway, so it is more than just a bugfix. If you still need an extremely quick fix, please try to clone the git repo on the develop branch, which can even be done with pip:

    pip install git+https://github.com/e2nIEE/pandapipes.git@develop

or otherwise go to your pandapipes code and change the following: in pandapipes/multinet/timeseries/run_timeseries_multinet.py, line 94:
from `print_progress_bar(0, len(time_steps), prefix='Progress:', suffix='Complete', length=50)`
to `ts_variables['progress_bar'] = tqdm.tqdm(total=len(time_steps))`
Best regards

**Comment by dlohmeier** [comment]
With the new release v0.7.0 this error is fixed.
